target-version = "py312"

[lint]
ignore = [
    "B008",
    "BLE001",
    "PLW1510",
    "SIM117",
    "B017",
    "F841",
    "I001",
    "UP006",
    "UP007",
    "UP017",
    "UP035",
    "RUF022",
]
